disabled_rules: # rule identifiers to exclude from running
  - line_length
  - file_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - fastlane
  - DerivedData

type_name:
  allowed_symbols: "_"
  
type_body_length:
 - 300 # warning
 - 500 # error

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length: 50
  excluded:
    - id
